# ================ DB config ============================
import os
import sys

PACKAGE_PARENT = '..'
SCRIPT_DIR = os.path.dirname(os.path.realpath(os.path.join(os.getcwd(), os.path.expanduser(__file__))))
sys.path.append(os.path.normpath(os.path.join(SCRIPT_DIR, PACKAGE_PARENT)))

from Utils.DB_config import ConfigQuant

# ================== Process config =======================


HS300QuoteConf = {
    'table_name': 'HS300_QUOTE',
    'date_field': 'date',
    'fields': ['close', 'amount']
}


allMergeDataConf = [
    # ======================  HS300
    {
        'table_name': 'DERI_HS300',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                   'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                   'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                   'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                   'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                   'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                   'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                   'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                   'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                   'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                   'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                   'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                   'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D',
                   'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D',
                   'AD_DIFF_7D', 'AD_DIFF_14D', 'AD_DIFF_21D', 'AD_DIFF_28D',
                   'ADX_7D', 'ADX_14D', 'ADX_21D', 'ADX_28D',
                   'CCI_7D', 'CCI_14D', 'CCI_21D', 'CCI_28D',
                   'RSI_7D', 'RSI_14D', 'RSI_21D', 'RSI_28D',
                   'STOCH_K_7D', 'STOCH_K_14D', 'STOCH_K_21D', 'STOCH_K_28D',
                   'STOCH_D_7D', 'STOCH_D_14D', 'STOCH_D_21D', 'STOCH_D_28D',
                   'WILLER_7D', 'WILLER_14D', 'WILLER_21D', 'WILLER_28D',
                   'VR_7D', 'VR_14D', 'VR_21D', 'VR_28D',
                   'VOLUME_RATIO'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'HS300',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_HS300',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['AMTMA_2D', 'AMTMA_5D', 'AMTMA_10D', 'AMTMA_20D', 'AMTMA_30D', 'AMTMA_60D', 'AMTMA_120D',
                        'AMTMA_250D',
                        'AMTMA_DIFF_2D', 'AMTMA_DIFF_SIGN_2D', 'AMTMA_DIFF_PLUS_COUNT_2D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_2D', 'AMTMA_DIFF_CON_PLUS_COUNT_2D',
                        'AMTMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTMA_DIFF_5D', 'AMTMA_DIFF_SIGN_5D', 'AMTMA_DIFF_PLUS_COUNT_5D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_5D', 'AMTMA_DIFF_CON_PLUS_COUNT_5D',
                        'AMTMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTMA_DIFF_10D', 'AMTMA_DIFF_SIGN_10D', 'AMTMA_DIFF_PLUS_COUNT_10D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_10D', 'AMTMA_DIFF_CON_PLUS_COUNT_10D',
                        'AMTMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTMA_DIFF_20D', 'AMTMA_DIFF_SIGN_20D', 'AMTMA_DIFF_PLUS_COUNT_20D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_20D', 'AMTMA_DIFF_CON_PLUS_COUNT_20D',
                        'AMTMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTMA_DIFF_30D', 'AMTMA_DIFF_SIGN_30D', 'AMTMA_DIFF_PLUS_COUNT_30D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_30D', 'AMTMA_DIFF_CON_PLUS_COUNT_30D',
                        'AMTMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTMA_DIFF_60D', 'AMTMA_DIFF_SIGN_60D', 'AMTMA_DIFF_PLUS_COUNT_60D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_60D', 'AMTMA_DIFF_CON_PLUS_COUNT_60D',
                        'AMTMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTMA_DIFF_120D', 'AMTMA_DIFF_SIGN_120D', 'AMTMA_DIFF_PLUS_COUNT_120D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_120D', 'AMTMA_DIFF_CON_PLUS_COUNT_120D',
                        'AMTMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTMA_DIFF_250D', 'AMTMA_DIFF_SIGN_250D', 'AMTMA_DIFF_PLUS_COUNT_250D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_250D', 'AMTMA_DIFF_CON_PLUS_COUNT_250D',
                        'AMTMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'AMTWMA_2D', 'AMTWMA_5D', 'AMTWMA_10D', 'AMTWMA_20D', 'AMTWMA_30D', 'AMTWMA_60D', 'AMTWMA_120D',
                        'AMTWMA_250D',
                        'AMTWMA_DIFF_2D', 'AMTWMA_DIFF_SIGN_2D', 'AMTWMA_DIFF_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_2D', 'AMTWMA_DIFF_CON_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTWMA_DIFF_5D', 'AMTWMA_DIFF_SIGN_5D', 'AMTWMA_DIFF_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_5D', 'AMTWMA_DIFF_CON_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTWMA_DIFF_10D', 'AMTWMA_DIFF_SIGN_10D', 'AMTWMA_DIFF_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_10D', 'AMTWMA_DIFF_CON_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTWMA_DIFF_20D', 'AMTWMA_DIFF_SIGN_20D', 'AMTWMA_DIFF_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_20D', 'AMTWMA_DIFF_CON_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTWMA_DIFF_30D', 'AMTWMA_DIFF_SIGN_30D', 'AMTWMA_DIFF_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_30D', 'AMTWMA_DIFF_CON_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTWMA_DIFF_60D', 'AMTWMA_DIFF_SIGN_60D', 'AMTWMA_DIFF_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_60D', 'AMTWMA_DIFF_CON_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTWMA_DIFF_120D', 'AMTWMA_DIFF_SIGN_120D', 'AMTWMA_DIFF_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_120D', 'AMTWMA_DIFF_CON_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTWMA_DIFF_250D', 'AMTWMA_DIFF_SIGN_250D', 'AMTWMA_DIFF_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_250D', 'AMTWMA_DIFF_CON_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'time_stamp'],
        'prefix': 'HS300',
        'condition': ""
    },

    # ================================ CPI

    {
        'table_name': 'DONGFANGCAIFU_CPI',
        'fields': ['date', 'oncountrywide_YOY', 'oncountrywide_MOM'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'CPI',
        'condition': ""
    },

    # ================================= US stock index

    {
        'table_name': 'DERI_NASDAQ',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                   'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                   'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                   'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                   'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                   'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                   'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                   'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                   'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                   'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                   'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                   'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                   'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D',
                   'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'NASDAQ',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_NASDAQ',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'NASDAQ',
        'condition': ""
    },

    {
        'table_name': 'DERI_SP500',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                   'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                   'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                   'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                   'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                   'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                   'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                   'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                   'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                   'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                   'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                   'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                   'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D',
                   'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'SP500',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_SP500',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'SP500',
        'condition': ""
    },

    {
        'table_name': 'DERI_DOW_JONES',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                   'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                   'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                   'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                   'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                   'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                   'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                   'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                   'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                   'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                   'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                   'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                   'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D',
                   'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'DOW',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_DOW_JONES',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'DOW',
        'condition': ""
    },

    # ==================================== Gold

    {
        'table_name': 'PRECIOUS_METAL',
        'fields': ['date', 'amount'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'AU',
        'condition': "`code`='AU99.99'"
    },

    {
        'table_name': 'DERI_AU',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D',
                   'AD_DIFF_7D', 'AD_DIFF_14D', 'AD_DIFF_21D', 'AD_DIFF_28D',
                   'ADX_7D', 'ADX_14D', 'ADX_21D', 'ADX_28D',
                   'CCI_7D', 'CCI_14D', 'CCI_21D', 'CCI_28D',
                   'RSI_7D', 'RSI_14D', 'RSI_21D', 'RSI_28D',
                   'STOCH_K_7D', 'STOCH_K_14D', 'STOCH_K_21D', 'STOCH_K_28D',
                   'STOCH_D_7D', 'STOCH_D_14D', 'STOCH_D_21D', 'STOCH_D_28D',
                   'WILLER_7D', 'WILLER_14D', 'WILLER_21D', 'WILLER_28D',
                   'VR_7D', 'VR_14D', 'VR_21D', 'VR_28D'
                   ],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'AU',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_AU',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['AMTMA_2D', 'AMTMA_5D', 'AMTMA_10D', 'AMTMA_20D', 'AMTMA_30D', 'AMTMA_60D', 'AMTMA_120D', 'AMTMA_250D',
                        'AMTMA_DIFF_2D', 'AMTMA_DIFF_SIGN_2D', 'AMTMA_DIFF_PLUS_COUNT_2D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_2D', 'AMTMA_DIFF_CON_PLUS_COUNT_2D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTMA_DIFF_5D', 'AMTMA_DIFF_SIGN_5D', 'AMTMA_DIFF_PLUS_COUNT_5D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_5D', 'AMTMA_DIFF_CON_PLUS_COUNT_5D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTMA_DIFF_10D', 'AMTMA_DIFF_SIGN_10D', 'AMTMA_DIFF_PLUS_COUNT_10D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_10D', 'AMTMA_DIFF_CON_PLUS_COUNT_10D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTMA_DIFF_20D', 'AMTMA_DIFF_SIGN_20D', 'AMTMA_DIFF_PLUS_COUNT_20D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_20D', 'AMTMA_DIFF_CON_PLUS_COUNT_20D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTMA_DIFF_30D', 'AMTMA_DIFF_SIGN_30D', 'AMTMA_DIFF_PLUS_COUNT_30D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_30D', 'AMTMA_DIFF_CON_PLUS_COUNT_30D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTMA_DIFF_60D', 'AMTMA_DIFF_SIGN_60D', 'AMTMA_DIFF_PLUS_COUNT_60D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_60D', 'AMTMA_DIFF_CON_PLUS_COUNT_60D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTMA_DIFF_120D', 'AMTMA_DIFF_SIGN_120D', 'AMTMA_DIFF_PLUS_COUNT_120D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_120D', 'AMTMA_DIFF_CON_PLUS_COUNT_120D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTMA_DIFF_250D', 'AMTMA_DIFF_SIGN_250D', 'AMTMA_DIFF_PLUS_COUNT_250D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_250D', 'AMTMA_DIFF_CON_PLUS_COUNT_250D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'AMTWMA_2D', 'AMTWMA_5D', 'AMTWMA_10D', 'AMTWMA_20D', 'AMTWMA_30D', 'AMTWMA_60D', 'AMTWMA_120D', 'AMTWMA_250D',
                        'AMTWMA_DIFF_2D', 'AMTWMA_DIFF_SIGN_2D', 'AMTWMA_DIFF_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_2D', 'AMTWMA_DIFF_CON_PLUS_COUNT_2D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTWMA_DIFF_5D', 'AMTWMA_DIFF_SIGN_5D', 'AMTWMA_DIFF_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_5D', 'AMTWMA_DIFF_CON_PLUS_COUNT_5D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTWMA_DIFF_10D', 'AMTWMA_DIFF_SIGN_10D', 'AMTWMA_DIFF_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_10D', 'AMTWMA_DIFF_CON_PLUS_COUNT_10D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTWMA_DIFF_20D', 'AMTWMA_DIFF_SIGN_20D', 'AMTWMA_DIFF_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_20D', 'AMTWMA_DIFF_CON_PLUS_COUNT_20D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTWMA_DIFF_30D', 'AMTWMA_DIFF_SIGN_30D', 'AMTWMA_DIFF_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_30D', 'AMTWMA_DIFF_CON_PLUS_COUNT_30D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTWMA_DIFF_60D', 'AMTWMA_DIFF_SIGN_60D', 'AMTWMA_DIFF_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_60D', 'AMTWMA_DIFF_CON_PLUS_COUNT_60D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTWMA_DIFF_120D', 'AMTWMA_DIFF_SIGN_120D', 'AMTWMA_DIFF_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_120D', 'AMTWMA_DIFF_CON_PLUS_COUNT_120D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTWMA_DIFF_250D', 'AMTWMA_DIFF_SIGN_250D', 'AMTWMA_DIFF_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_250D', 'AMTWMA_DIFF_CON_PLUS_COUNT_250D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'time_stamp'],
        'prefix': 'AU',
        'condition': ""
    },

    # ================================  Shibor
    {
        'table_name': 'SHIBOR_NEW',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'SHIBOR',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_ON',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_ON',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_1W',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_1D',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_2W',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_2D',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_1M',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_1M',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_3M',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_3M',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_6M',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_6M',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_9M',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_9M',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_1Y',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_1Y',
        'condition': ""
    },

    # =============================== Brent Crude Oil
    {
        'table_name': 'BRENT_QUOTE',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'BRENT',
        'condition': ""
    },

    {
        'table_name': 'DERI_BRENT',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'BRENT',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_BRENT',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'BRENT',
        'condition': ""
    },

    # =============================== GEB
    {
        'table_name': 'STOCK_MARKET_INDEX_QUOTE',
        'fields': ['date', 'close', 'amount'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'GEB',
        'condition': "`market` = 'GEB'"
    },

    {
        'table_name': 'DERI_MARKET_INDEX',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D',
                   'AD_DIFF_7D', 'AD_DIFF_14D', 'AD_DIFF_21D', 'AD_DIFF_28D',
                   'ADX_7D', 'ADX_14D', 'ADX_21D', 'ADX_28D',
                   'CCI_7D', 'CCI_14D', 'CCI_21D', 'CCI_28D',
                   'RSI_7D', 'RSI_14D', 'RSI_21D', 'RSI_28D',
                   'STOCH_K_7D', 'STOCH_K_14D', 'STOCH_K_21D', 'STOCH_K_28D',
                   'STOCH_D_7D', 'STOCH_D_14D', 'STOCH_D_21D', 'STOCH_D_28D',
                   'WILLER_7D', 'WILLER_14D', 'WILLER_21D', 'WILLER_28D',
                   'VR_7D', 'VR_14D', 'VR_21D', 'VR_28D',
                   'VOLUME_RATIO', 'AMPLITUDE_1D', 'AMPLITUDE_2D', 'AMPLITUDE_5D', 'AMPLITUDE_10D',
                   'AMPLITUDE_20D', 'AMPLITUDE_30D', 'AMPLITUDE_60D'
                   ],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'GEB',
        'condition': "`market` = 'GEB'"
    },

    {
        'table_name': 'DERI_STAT_MARKET_INDEX',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['AMTMA_2D', 'AMTMA_5D', 'AMTMA_10D', 'AMTMA_20D', 'AMTMA_30D', 'AMTMA_60D', 'AMTMA_120D', 'AMTMA_250D',
                        'AMTMA_DIFF_2D', 'AMTMA_DIFF_SIGN_2D', 'AMTMA_DIFF_PLUS_COUNT_2D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_2D', 'AMTMA_DIFF_CON_PLUS_COUNT_2D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTMA_DIFF_5D', 'AMTMA_DIFF_SIGN_5D', 'AMTMA_DIFF_PLUS_COUNT_5D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_5D', 'AMTMA_DIFF_CON_PLUS_COUNT_5D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTMA_DIFF_10D', 'AMTMA_DIFF_SIGN_10D', 'AMTMA_DIFF_PLUS_COUNT_10D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_10D', 'AMTMA_DIFF_CON_PLUS_COUNT_10D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTMA_DIFF_20D', 'AMTMA_DIFF_SIGN_20D', 'AMTMA_DIFF_PLUS_COUNT_20D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_20D', 'AMTMA_DIFF_CON_PLUS_COUNT_20D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTMA_DIFF_30D', 'AMTMA_DIFF_SIGN_30D', 'AMTMA_DIFF_PLUS_COUNT_30D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_30D', 'AMTMA_DIFF_CON_PLUS_COUNT_30D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTMA_DIFF_60D', 'AMTMA_DIFF_SIGN_60D', 'AMTMA_DIFF_PLUS_COUNT_60D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_60D', 'AMTMA_DIFF_CON_PLUS_COUNT_60D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTMA_DIFF_120D', 'AMTMA_DIFF_SIGN_120D', 'AMTMA_DIFF_PLUS_COUNT_120D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_120D', 'AMTMA_DIFF_CON_PLUS_COUNT_120D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTMA_DIFF_250D', 'AMTMA_DIFF_SIGN_250D', 'AMTMA_DIFF_PLUS_COUNT_250D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_250D', 'AMTMA_DIFF_CON_PLUS_COUNT_250D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'AMTWMA_2D', 'AMTWMA_5D', 'AMTWMA_10D', 'AMTWMA_20D', 'AMTWMA_30D', 'AMTWMA_60D', 'AMTWMA_120D', 'AMTWMA_250D',
                        'AMTWMA_DIFF_2D', 'AMTWMA_DIFF_SIGN_2D', 'AMTWMA_DIFF_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_2D', 'AMTWMA_DIFF_CON_PLUS_COUNT_2D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTWMA_DIFF_5D', 'AMTWMA_DIFF_SIGN_5D', 'AMTWMA_DIFF_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_5D', 'AMTWMA_DIFF_CON_PLUS_COUNT_5D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTWMA_DIFF_10D', 'AMTWMA_DIFF_SIGN_10D', 'AMTWMA_DIFF_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_10D', 'AMTWMA_DIFF_CON_PLUS_COUNT_10D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTWMA_DIFF_20D', 'AMTWMA_DIFF_SIGN_20D', 'AMTWMA_DIFF_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_20D', 'AMTWMA_DIFF_CON_PLUS_COUNT_20D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTWMA_DIFF_30D', 'AMTWMA_DIFF_SIGN_30D', 'AMTWMA_DIFF_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_30D', 'AMTWMA_DIFF_CON_PLUS_COUNT_30D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTWMA_DIFF_60D', 'AMTWMA_DIFF_SIGN_60D', 'AMTWMA_DIFF_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_60D', 'AMTWMA_DIFF_CON_PLUS_COUNT_60D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTWMA_DIFF_120D', 'AMTWMA_DIFF_SIGN_120D', 'AMTWMA_DIFF_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_120D', 'AMTWMA_DIFF_CON_PLUS_COUNT_120D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTWMA_DIFF_250D', 'AMTWMA_DIFF_SIGN_250D', 'AMTWMA_DIFF_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_250D', 'AMTWMA_DIFF_CON_PLUS_COUNT_250D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'market', 'time_stamp'],
        'prefix': 'GEB',
        'condition': "`market` = 'GEB'"
    },

    # =============================== SMEB
    {
        'table_name': 'STOCK_MARKET_INDEX_QUOTE',
        'fields': ['date', 'close', 'amount'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'SMEB',
        'condition': "`market` = 'SMEB'"
    },

    {
        'table_name': 'DERI_MARKET_INDEX',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D',
                   'AD_DIFF_7D', 'AD_DIFF_14D', 'AD_DIFF_21D', 'AD_DIFF_28D',
                   'ADX_7D', 'ADX_14D', 'ADX_21D', 'ADX_28D',
                   'CCI_7D', 'CCI_14D', 'CCI_21D', 'CCI_28D',
                   'RSI_7D', 'RSI_14D', 'RSI_21D', 'RSI_28D',
                   'STOCH_K_7D', 'STOCH_K_14D', 'STOCH_K_21D', 'STOCH_K_28D',
                   'STOCH_D_7D', 'STOCH_D_14D', 'STOCH_D_21D', 'STOCH_D_28D',
                   'WILLER_7D', 'WILLER_14D', 'WILLER_21D', 'WILLER_28D',
                   'VR_7D', 'VR_14D', 'VR_21D', 'VR_28D',
                   'VOLUME_RATIO', 'AMPLITUDE_1D', 'AMPLITUDE_2D', 'AMPLITUDE_5D', 'AMPLITUDE_10D',
                   'AMPLITUDE_20D', 'AMPLITUDE_30D', 'AMPLITUDE_60D'
                   ],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'SMEB',
        'condition': "`market` = 'SMEB'"
    },

    {
        'table_name': 'DERI_STAT_MARKET_INDEX',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['AMTMA_2D', 'AMTMA_5D', 'AMTMA_10D', 'AMTMA_20D', 'AMTMA_30D', 'AMTMA_60D', 'AMTMA_120D', 'AMTMA_250D',
                        'AMTMA_DIFF_2D', 'AMTMA_DIFF_SIGN_2D', 'AMTMA_DIFF_PLUS_COUNT_2D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_2D', 'AMTMA_DIFF_CON_PLUS_COUNT_2D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTMA_DIFF_5D', 'AMTMA_DIFF_SIGN_5D', 'AMTMA_DIFF_PLUS_COUNT_5D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_5D', 'AMTMA_DIFF_CON_PLUS_COUNT_5D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTMA_DIFF_10D', 'AMTMA_DIFF_SIGN_10D', 'AMTMA_DIFF_PLUS_COUNT_10D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_10D', 'AMTMA_DIFF_CON_PLUS_COUNT_10D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTMA_DIFF_20D', 'AMTMA_DIFF_SIGN_20D', 'AMTMA_DIFF_PLUS_COUNT_20D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_20D', 'AMTMA_DIFF_CON_PLUS_COUNT_20D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTMA_DIFF_30D', 'AMTMA_DIFF_SIGN_30D', 'AMTMA_DIFF_PLUS_COUNT_30D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_30D', 'AMTMA_DIFF_CON_PLUS_COUNT_30D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTMA_DIFF_60D', 'AMTMA_DIFF_SIGN_60D', 'AMTMA_DIFF_PLUS_COUNT_60D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_60D', 'AMTMA_DIFF_CON_PLUS_COUNT_60D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTMA_DIFF_120D', 'AMTMA_DIFF_SIGN_120D', 'AMTMA_DIFF_PLUS_COUNT_120D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_120D', 'AMTMA_DIFF_CON_PLUS_COUNT_120D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTMA_DIFF_250D', 'AMTMA_DIFF_SIGN_250D', 'AMTMA_DIFF_PLUS_COUNT_250D',
                        'AMTMA_DIFF_NEGATIVE_COUNT_250D', 'AMTMA_DIFF_CON_PLUS_COUNT_250D', 'AMTMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'AMTWMA_2D', 'AMTWMA_5D', 'AMTWMA_10D', 'AMTWMA_20D', 'AMTWMA_30D', 'AMTWMA_60D', 'AMTWMA_120D', 'AMTWMA_250D',
                        'AMTWMA_DIFF_2D', 'AMTWMA_DIFF_SIGN_2D', 'AMTWMA_DIFF_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_2D', 'AMTWMA_DIFF_CON_PLUS_COUNT_2D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTWMA_DIFF_5D', 'AMTWMA_DIFF_SIGN_5D', 'AMTWMA_DIFF_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_5D', 'AMTWMA_DIFF_CON_PLUS_COUNT_5D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTWMA_DIFF_10D', 'AMTWMA_DIFF_SIGN_10D', 'AMTWMA_DIFF_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_10D', 'AMTWMA_DIFF_CON_PLUS_COUNT_10D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTWMA_DIFF_20D', 'AMTWMA_DIFF_SIGN_20D', 'AMTWMA_DIFF_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_20D', 'AMTWMA_DIFF_CON_PLUS_COUNT_20D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTWMA_DIFF_30D', 'AMTWMA_DIFF_SIGN_30D', 'AMTWMA_DIFF_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_30D', 'AMTWMA_DIFF_CON_PLUS_COUNT_30D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTWMA_DIFF_60D', 'AMTWMA_DIFF_SIGN_60D', 'AMTWMA_DIFF_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_60D', 'AMTWMA_DIFF_CON_PLUS_COUNT_60D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTWMA_DIFF_120D', 'AMTWMA_DIFF_SIGN_120D', 'AMTWMA_DIFF_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_120D', 'AMTWMA_DIFF_CON_PLUS_COUNT_120D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTWMA_DIFF_250D', 'AMTWMA_DIFF_SIGN_250D', 'AMTWMA_DIFF_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_250D', 'AMTWMA_DIFF_CON_PLUS_COUNT_250D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'market', 'time_stamp'],
        'prefix': 'SMEB',
        'condition': "`market` = 'SMEB'"
    },

    # ================================== finance cash and security
    {
        'table_name': 'FINANCE_CASH_AND_SECURITY',
        'fields': ['date', 'OUTSTANDING_CASH_BALANCE', 'OUTSTANDING_SECURITY_BALANCE', 'OUTSTANDING_CASH_TO_FREE_CAP'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix':'',
        'condition': ''
    },

    # =================================== macroeconomic tushare
    {
        'table_name': 'MACROECONOMIC_TUSHARE',
        'fields': ['date', 'm0_yoy', 'm1_yoy', 'm2_yoy', 'sd_yoy', 'gdp_yoy', 'pi_yoy', 'si_yoy', 'ti_yoy'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix':'',
        'condition': ''
    },

    {
        'table_name': 'DERI_MACROECONOMIC_TUSHARE',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['year', 'season', 'month', 'time_stamp'],
        'prefix': '',
        'condition': ''
    },

]