# ================ DB config ============================
import os
import sys

PACKAGE_PARENT = '..'
SCRIPT_DIR = os.path.dirname(os.path.realpath(os.path.join(os.getcwd(), os.path.expanduser(__file__))))
sys.path.append(os.path.normpath(os.path.join(SCRIPT_DIR, PACKAGE_PARENT)))

from Utils.DB_config import ConfigQuant

# ================== Process config =======================


stockQuoteConf = {
    'table_name': 'STOCK_FORWARD_ADJ_QUOTE',
    'fields': ['date', 'code', 'amount', 'turnover']
}


allMergeDataConf = [
    {
        'table_name': 'STOCK_UNADJUSTED_QUOTE',
        'fields': ['date', 'code', 'close'],
        'merge_fields': ['date', 'code'],
        'drop_fields': [],
        'prefix': '',
        'condition': ''
    },

    {
        'table_name': 'STOCK_INDUSTRY',
        'fields': ['date', 'code', 'industry'],
        'merge_fields': ['date', 'code'],
        'drop_fields': [],
        'prefix':'',
        'condition': ''
    },

    {
        'table_name': 'STOCK_FUNDAMENTAL_TTM',
        'fields': ['date', 'code', 'PE_TTM', 'PS_TTM'],
        'merge_fields': ['date', 'code'],
        'drop_fields': [],
        'prefix': '',
        'condition': ''
    },

    {
        'table_name': 'STOCK_FUNDAMENTAL_BASIC',
        'fields': ['date', 'code', 'PB'],
        'merge_fields': ['date', 'code'],
        'drop_fields': [],
        'prefix': '',
        'condition': ''
    },

    {
        'table_name': 'DERI_STOCK_STAT_FUNDAMENTAL_INDICATORS',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['time_stamp'],
        'prefix': '',
        'condition': ''
    },

    {
        'table_name': 'STOCK_FUNDAMENTAL_DAILY_TUSHARE',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['fiscal_year', 'fiscal_season', 'report_date', 'time_stamp'],
        'prefix': '',
        'condition': ''
    },

    {
        'table_name': 'DERI_STOCK_STAT_TECH_INDICATORS',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['AMTEMA_2D', 'AMTEMA_5D', 'AMTEMA_10D', 'AMTEMA_20D', 'AMTEMA_30D', 'AMTEMA_60D', 'AMTEMA_120D', 'AMTEMA_250D',
                        'AMTEMA_DIFF_2D', 'AMTEMA_DIFF_SIGN_2D', 'AMTEMA_DIFF_PLUS_COUNT_2D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_2D', 'AMTEMA_DIFF_CON_PLUS_COUNT_2D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTEMA_DIFF_5D', 'AMTEMA_DIFF_SIGN_5D', 'AMTEMA_DIFF_PLUS_COUNT_5D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_5D', 'AMTEMA_DIFF_CON_PLUS_COUNT_5D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTEMA_DIFF_10D', 'AMTEMA_DIFF_SIGN_10D', 'AMTEMA_DIFF_PLUS_COUNT_10D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_10D', 'AMTEMA_DIFF_CON_PLUS_COUNT_10D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTEMA_DIFF_20D', 'AMTEMA_DIFF_SIGN_20D', 'AMTEMA_DIFF_PLUS_COUNT_20D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_20D', 'AMTEMA_DIFF_CON_PLUS_COUNT_20D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTEMA_DIFF_30D', 'AMTEMA_DIFF_SIGN_30D', 'AMTEMA_DIFF_PLUS_COUNT_30D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_30D', 'AMTEMA_DIFF_CON_PLUS_COUNT_30D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTEMA_DIFF_60D', 'AMTEMA_DIFF_SIGN_60D', 'AMTEMA_DIFF_PLUS_COUNT_60D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_60D', 'AMTEMA_DIFF_CON_PLUS_COUNT_60D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTEMA_DIFF_120D', 'AMTEMA_DIFF_SIGN_120D', 'AMTEMA_DIFF_PLUS_COUNT_120D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_120D', 'AMTEMA_DIFF_CON_PLUS_COUNT_120D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTEMA_DIFF_250D', 'AMTEMA_DIFF_SIGN_250D', 'AMTEMA_DIFF_PLUS_COUNT_250D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_250D', 'AMTEMA_DIFF_CON_PLUS_COUNT_250D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'AMTWMA_2D', 'AMTWMA_5D', 'AMTWMA_10D', 'AMTWMA_20D', 'AMTWMA_30D', 'AMTWMA_60D', 'AMTWMA_120D', 'AMTWMA_250D',
                        'AMTWMA_DIFF_2D', 'AMTWMA_DIFF_SIGN_2D', 'AMTWMA_DIFF_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_2D', 'AMTWMA_DIFF_CON_PLUS_COUNT_2D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTWMA_DIFF_5D', 'AMTWMA_DIFF_SIGN_5D', 'AMTWMA_DIFF_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_5D', 'AMTWMA_DIFF_CON_PLUS_COUNT_5D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTWMA_DIFF_10D', 'AMTWMA_DIFF_SIGN_10D', 'AMTWMA_DIFF_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_10D', 'AMTWMA_DIFF_CON_PLUS_COUNT_10D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTWMA_DIFF_20D', 'AMTWMA_DIFF_SIGN_20D', 'AMTWMA_DIFF_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_20D', 'AMTWMA_DIFF_CON_PLUS_COUNT_20D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTWMA_DIFF_30D', 'AMTWMA_DIFF_SIGN_30D', 'AMTWMA_DIFF_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_30D', 'AMTWMA_DIFF_CON_PLUS_COUNT_30D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTWMA_DIFF_60D', 'AMTWMA_DIFF_SIGN_60D', 'AMTWMA_DIFF_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_60D', 'AMTWMA_DIFF_CON_PLUS_COUNT_60D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTWMA_DIFF_120D', 'AMTWMA_DIFF_SIGN_120D', 'AMTWMA_DIFF_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_120D', 'AMTWMA_DIFF_CON_PLUS_COUNT_120D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTWMA_DIFF_250D', 'AMTWMA_DIFF_SIGN_250D', 'AMTWMA_DIFF_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_250D', 'AMTWMA_DIFF_CON_PLUS_COUNT_250D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'time_stamp'],
        'prefix': '',
        'condition': ''
    },

    {
        'table_name': 'DERI_STOCK_TECH_INDICATORS',
        'fields': ['date', 'code', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D',
                   'AD_DIFF_7D', 'AD_DIFF_14D', 'AD_DIFF_21D', 'AD_DIFF_28D',
                   'ADX_7D', 'ADX_14D', 'ADX_21D', 'ADX_28D',
                   'CCI_7D', 'CCI_14D', 'CCI_21D', 'CCI_28D',
                   'RSI_7D', 'RSI_14D', 'RSI_21D', 'RSI_28D',
                   'STOCH_K_7D', 'STOCH_K_14D', 'STOCH_K_21D', 'STOCH_K_28D',
                   'STOCH_D_7D', 'STOCH_D_14D', 'STOCH_D_21D', 'STOCH_D_28D',
                   'WILLER_7D', 'WILLER_14D', 'WILLER_21D', 'WILLER_28D',
                   'VR_7D', 'VR_14D', 'VR_21D', 'VR_28D',
                   'VOLUME_RATIO', 'TURNOVER_ROLLING_SUM_2D', 'TURNOVER_ROLLING_SUM_5D',
                   'TURNOVER_ROLLING_SUM_10D', 'TURNOVER_ROLLING_SUM_20D', 'TURNOVER_ROLLING_SUM_30D', 'TURNOVER_ROLLING_SUM_60D',
                   'AMPLITUDE_1D', 'AMPLITUDE_2D', 'AMPLITUDE_5D', 'AMPLITUDE_10D', 'AMPLITUDE_20D', 'AMPLITUDE_30D', 'AMPLITUDE_60D'
                   ],
        'merge_fields': ['date', 'code'],
        'drop_fields': [],
        'prefix': '',
        'condition': ''
    },

    {
        'table_name': 'DERI_STOCK_RANKING_AREA',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['time_stamp'],
        'prefix':'AREA',
        'condition': ''
    },

    {
        'table_name': 'DERI_STOCK_RANKING_INDUSTRY',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['time_stamp'],
        'prefix':'INDUSTRY',
        'condition': ''
    },

    {
        'table_name': 'DERI_STOCK_RANKING_MARKET',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['time_stamp'],
        'prefix':'MARKET',
        'condition': ''
    },

    {
        'table_name': 'DERI_STOCK_RANKING_ALL_STOCKS',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['time_stamp'],
        'prefix':'ALL',
        'condition': ''
    },

    {
        'table_name': 'DERI_AREA_EXCESSIVE_RET',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['time_stamp'],
        'prefix':'AREA',
        'condition': ''
    },

    {
        'table_name': 'DERI_INDUSTRY_EXCESSIVE_RET',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['time_stamp'],
        'prefix':'INDUSTRY',
        'condition': ''
    },

    {
        'table_name': 'DERI_MARKET_EXCESSIVE_RET',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['time_stamp'],
        'prefix': 'MARKET',
        'condition': ''
    },

    {
        'table_name': 'DERI_HS300_EXCESSIVE_RET',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['time_stamp'],
        'prefix': 'HS300',
        'condition': ''
    },

    {
        'table_name': 'STOCK_BETA',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': ['time_stamp'],
        'prefix': '',
        'condition': ''
    },

    {
        'table_name': 'STOCK_DAY_COUNT',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': [],
        'prefix': '',
        'condition': ''
    },

    {
        'table_name': 'STOCK_VALUE',
        'fields': '*',
        'merge_fields': ['date', 'code'],
        'drop_fields': [],
        'prefix': '',
        'condition': ''
    },

    {
        'table_name': 'PRECIOUS_METAL',
        'fields': ['date', 'amount'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'AU',
        'condition': "`code`='AU99.99'"
    },

    {
        'table_name': 'FUND_INDEX',
        'fields': ['date', 'amount'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'FUND',
        'condition': ""
    },

    {
        'table_name': 'DERI_AU',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D',
                   'AD_DIFF_7D', 'AD_DIFF_14D', 'AD_DIFF_21D', 'AD_DIFF_28D',
                   'ADX_7D', 'ADX_14D', 'ADX_21D', 'ADX_28D',
                   'CCI_7D', 'CCI_14D', 'CCI_21D', 'CCI_28D',
                   'RSI_7D', 'RSI_14D', 'RSI_21D', 'RSI_28D',
                   'STOCH_K_7D', 'STOCH_K_14D', 'STOCH_K_21D', 'STOCH_K_28D',
                   'STOCH_D_7D', 'STOCH_D_14D', 'STOCH_D_21D', 'STOCH_D_28D',
                   'WILLER_7D', 'WILLER_14D', 'WILLER_21D', 'WILLER_28D',
                   'VR_7D', 'VR_14D', 'VR_21D', 'VR_28D'
                   ],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'AU',
        'condition': ""
    },

    {
        'table_name': 'DERI_FUND_INDEX_SSE_C',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D',
                   'AD_DIFF_7D', 'AD_DIFF_14D', 'AD_DIFF_21D', 'AD_DIFF_28D',
                   'ADX_7D', 'ADX_14D', 'ADX_21D', 'ADX_28D',
                   'CCI_7D', 'CCI_14D', 'CCI_21D', 'CCI_28D',
                   'RSI_7D', 'RSI_14D', 'RSI_21D', 'RSI_28D',
                   'STOCH_K_7D', 'STOCH_K_14D', 'STOCH_K_21D', 'STOCH_K_28D',
                   'STOCH_D_7D', 'STOCH_D_14D', 'STOCH_D_21D', 'STOCH_D_28D',
                   'WILLER_7D', 'WILLER_14D', 'WILLER_21D', 'WILLER_28D',
                   'VR_7D', 'VR_14D', 'VR_21D', 'VR_28D'
                   ],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'FUND',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_AU',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['AMTEMA_2D', 'AMTEMA_5D', 'AMTEMA_10D', 'AMTEMA_20D', 'AMTEMA_30D', 'AMTEMA_60D', 'AMTEMA_120D', 'AMTEMA_250D',
                        'AMTEMA_DIFF_2D', 'AMTEMA_DIFF_SIGN_2D', 'AMTEMA_DIFF_PLUS_COUNT_2D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_2D', 'AMTEMA_DIFF_CON_PLUS_COUNT_2D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTEMA_DIFF_5D', 'AMTEMA_DIFF_SIGN_5D', 'AMTEMA_DIFF_PLUS_COUNT_5D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_5D', 'AMTEMA_DIFF_CON_PLUS_COUNT_5D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTEMA_DIFF_10D', 'AMTEMA_DIFF_SIGN_10D', 'AMTEMA_DIFF_PLUS_COUNT_10D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_10D', 'AMTEMA_DIFF_CON_PLUS_COUNT_10D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTEMA_DIFF_20D', 'AMTEMA_DIFF_SIGN_20D', 'AMTEMA_DIFF_PLUS_COUNT_20D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_20D', 'AMTEMA_DIFF_CON_PLUS_COUNT_20D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTEMA_DIFF_30D', 'AMTEMA_DIFF_SIGN_30D', 'AMTEMA_DIFF_PLUS_COUNT_30D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_30D', 'AMTEMA_DIFF_CON_PLUS_COUNT_30D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTEMA_DIFF_60D', 'AMTEMA_DIFF_SIGN_60D', 'AMTEMA_DIFF_PLUS_COUNT_60D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_60D', 'AMTEMA_DIFF_CON_PLUS_COUNT_60D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTEMA_DIFF_120D', 'AMTEMA_DIFF_SIGN_120D', 'AMTEMA_DIFF_PLUS_COUNT_120D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_120D', 'AMTEMA_DIFF_CON_PLUS_COUNT_120D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTEMA_DIFF_250D', 'AMTEMA_DIFF_SIGN_250D', 'AMTEMA_DIFF_PLUS_COUNT_250D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_250D', 'AMTEMA_DIFF_CON_PLUS_COUNT_250D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'AMTWMA_2D', 'AMTWMA_5D', 'AMTWMA_10D', 'AMTWMA_20D', 'AMTWMA_30D', 'AMTWMA_60D', 'AMTWMA_120D', 'AMTWMA_250D',
                        'AMTWMA_DIFF_2D', 'AMTWMA_DIFF_SIGN_2D', 'AMTWMA_DIFF_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_2D', 'AMTWMA_DIFF_CON_PLUS_COUNT_2D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTWMA_DIFF_5D', 'AMTWMA_DIFF_SIGN_5D', 'AMTWMA_DIFF_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_5D', 'AMTWMA_DIFF_CON_PLUS_COUNT_5D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTWMA_DIFF_10D', 'AMTWMA_DIFF_SIGN_10D', 'AMTWMA_DIFF_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_10D', 'AMTWMA_DIFF_CON_PLUS_COUNT_10D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTWMA_DIFF_20D', 'AMTWMA_DIFF_SIGN_20D', 'AMTWMA_DIFF_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_20D', 'AMTWMA_DIFF_CON_PLUS_COUNT_20D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTWMA_DIFF_30D', 'AMTWMA_DIFF_SIGN_30D', 'AMTWMA_DIFF_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_30D', 'AMTWMA_DIFF_CON_PLUS_COUNT_30D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTWMA_DIFF_60D', 'AMTWMA_DIFF_SIGN_60D', 'AMTWMA_DIFF_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_60D', 'AMTWMA_DIFF_CON_PLUS_COUNT_60D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTWMA_DIFF_120D', 'AMTWMA_DIFF_SIGN_120D', 'AMTWMA_DIFF_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_120D', 'AMTWMA_DIFF_CON_PLUS_COUNT_120D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTWMA_DIFF_250D', 'AMTWMA_DIFF_SIGN_250D', 'AMTWMA_DIFF_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_250D', 'AMTWMA_DIFF_CON_PLUS_COUNT_250D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'time_stamp'],
        'prefix': 'AU',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_FUND_INDEX_SSE_C',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['AMTEMA_2D', 'AMTEMA_5D', 'AMTEMA_10D', 'AMTEMA_20D', 'AMTEMA_30D', 'AMTEMA_60D', 'AMTEMA_120D', 'AMTEMA_250D',
                        'AMTEMA_DIFF_2D', 'AMTEMA_DIFF_SIGN_2D', 'AMTEMA_DIFF_PLUS_COUNT_2D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_2D', 'AMTEMA_DIFF_CON_PLUS_COUNT_2D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTEMA_DIFF_5D', 'AMTEMA_DIFF_SIGN_5D', 'AMTEMA_DIFF_PLUS_COUNT_5D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_5D', 'AMTEMA_DIFF_CON_PLUS_COUNT_5D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTEMA_DIFF_10D', 'AMTEMA_DIFF_SIGN_10D', 'AMTEMA_DIFF_PLUS_COUNT_10D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_10D', 'AMTEMA_DIFF_CON_PLUS_COUNT_10D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTEMA_DIFF_20D', 'AMTEMA_DIFF_SIGN_20D', 'AMTEMA_DIFF_PLUS_COUNT_20D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_20D', 'AMTEMA_DIFF_CON_PLUS_COUNT_20D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTEMA_DIFF_30D', 'AMTEMA_DIFF_SIGN_30D', 'AMTEMA_DIFF_PLUS_COUNT_30D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_30D', 'AMTEMA_DIFF_CON_PLUS_COUNT_30D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTEMA_DIFF_60D', 'AMTEMA_DIFF_SIGN_60D', 'AMTEMA_DIFF_PLUS_COUNT_60D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_60D', 'AMTEMA_DIFF_CON_PLUS_COUNT_60D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTEMA_DIFF_120D', 'AMTEMA_DIFF_SIGN_120D', 'AMTEMA_DIFF_PLUS_COUNT_120D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_120D', 'AMTEMA_DIFF_CON_PLUS_COUNT_120D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTEMA_DIFF_250D', 'AMTEMA_DIFF_SIGN_250D', 'AMTEMA_DIFF_PLUS_COUNT_250D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_250D', 'AMTEMA_DIFF_CON_PLUS_COUNT_250D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'AMTWMA_2D', 'AMTWMA_5D', 'AMTWMA_10D', 'AMTWMA_20D', 'AMTWMA_30D', 'AMTWMA_60D', 'AMTWMA_120D', 'AMTWMA_250D',
                        'AMTWMA_DIFF_2D', 'AMTWMA_DIFF_SIGN_2D', 'AMTWMA_DIFF_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_2D', 'AMTWMA_DIFF_CON_PLUS_COUNT_2D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTWMA_DIFF_5D', 'AMTWMA_DIFF_SIGN_5D', 'AMTWMA_DIFF_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_5D', 'AMTWMA_DIFF_CON_PLUS_COUNT_5D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTWMA_DIFF_10D', 'AMTWMA_DIFF_SIGN_10D', 'AMTWMA_DIFF_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_10D', 'AMTWMA_DIFF_CON_PLUS_COUNT_10D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTWMA_DIFF_20D', 'AMTWMA_DIFF_SIGN_20D', 'AMTWMA_DIFF_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_20D', 'AMTWMA_DIFF_CON_PLUS_COUNT_20D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTWMA_DIFF_30D', 'AMTWMA_DIFF_SIGN_30D', 'AMTWMA_DIFF_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_30D', 'AMTWMA_DIFF_CON_PLUS_COUNT_30D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTWMA_DIFF_60D', 'AMTWMA_DIFF_SIGN_60D', 'AMTWMA_DIFF_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_60D', 'AMTWMA_DIFF_CON_PLUS_COUNT_60D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTWMA_DIFF_120D', 'AMTWMA_DIFF_SIGN_120D', 'AMTWMA_DIFF_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_120D', 'AMTWMA_DIFF_CON_PLUS_COUNT_120D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTWMA_DIFF_250D', 'AMTWMA_DIFF_SIGN_250D', 'AMTWMA_DIFF_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_250D', 'AMTWMA_DIFF_CON_PLUS_COUNT_250D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'time_stamp'],
        'prefix': 'FUND',
        'condition': ""
    },

    {
        'table_name': 'SHIBOR_NEW',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'SHIBOR',
        'condition': ""
    },

    {
        'table_name': 'DERI_BRENT',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'BRENT',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_BRENT',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'BRENT',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_ON',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_ON',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_1W',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_1D',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_2W',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_2D',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_1M',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_1M',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_3M',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_3M',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_6M',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_6M',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_9M',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_9M',
        'condition': ""
    },

    {
        'table_name': 'DERI_MACRO_SHIBOR_1Y',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['MA_2D', 'MA_5D', 'MA_10D', 'MA_20D', 'MA_30D', 'MA_60D',
                        'MA_DIFF_2D', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                        'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'MA_DIFF_5D', 'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                        'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'MA_DIFF_10D', 'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                        'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'MA_DIFF_20D', 'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                        'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'MA_DIFF_30D', 'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                        'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'MA_DIFF_60D', 'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                        'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'WMA_2D', 'WMA_5D', 'WMA_10D', 'WMA_20D', 'WMA_30D', 'WMA_60D',
                        'WMA_DIFF_2D', 'WMA_DIFF_SIGN_2D', 'WMA_DIFF_PLUS_COUNT_2D',
                        'WMA_DIFF_NEGATIVE_COUNT_2D', 'WMA_DIFF_CON_PLUS_COUNT_2D', 'WMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'WMA_DIFF_5D', 'WMA_DIFF_SIGN_5D', 'WMA_DIFF_PLUS_COUNT_5D',
                        'WMA_DIFF_NEGATIVE_COUNT_5D', 'WMA_DIFF_CON_PLUS_COUNT_5D', 'WMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'WMA_DIFF_10D', 'WMA_DIFF_SIGN_10D', 'WMA_DIFF_PLUS_COUNT_10D',
                        'WMA_DIFF_NEGATIVE_COUNT_10D', 'WMA_DIFF_CON_PLUS_COUNT_10D', 'WMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'WMA_DIFF_20D', 'WMA_DIFF_SIGN_20D', 'WMA_DIFF_PLUS_COUNT_20D',
                        'WMA_DIFF_NEGATIVE_COUNT_20D', 'WMA_DIFF_CON_PLUS_COUNT_20D', 'WMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'WMA_DIFF_30D', 'WMA_DIFF_SIGN_30D', 'WMA_DIFF_PLUS_COUNT_30D',
                        'WMA_DIFF_NEGATIVE_COUNT_30D', 'WMA_DIFF_CON_PLUS_COUNT_30D', 'WMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'WMA_DIFF_60D', 'WMA_DIFF_SIGN_60D', 'WMA_DIFF_PLUS_COUNT_60D',
                        'WMA_DIFF_NEGATIVE_COUNT_60D', 'WMA_DIFF_CON_PLUS_COUNT_60D', 'WMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'time_stamp'],
        'prefix': 'SHIBOR_1Y',
        'condition': ""
    },

    {
        'table_name': 'DERI_NASDAQ',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'NASDAQ',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_NASDAQ',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'NASDAQ',
        'condition': ""
    },

    {
        'table_name': 'DERI_SP500',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'SP500',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_SP500',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'SP500',
        'condition': ""
    },

    {
        'table_name': 'DERI_DOW_JONES',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'DOW',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_DOW_JONES',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'DOW',
        'condition': ""
    },

    {
        'table_name': 'DONGFANGCAIFU_CPI',
        'fields': ['date', 'oncountrywide_YOY', 'oncountrywide_MOM'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'CPI',
        'condition': ""
    },
]


# merge  after categories are already merged
allMergeDataConf2 = [
    {
        'table_name': 'DERI_ALL_STOCK_RISE_RATIO',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['time_stamp'],
        'prefix': 'ALL',
        'condition': ""
    },

    {
        'table_name': 'DERI_AREA_RISE_RATIO',
        'fields': '*',
        'merge_fields': ['date', 'area'],
        'drop_fields': ['time_stamp'],
        'prefix': 'AREA',
        'condition': ""
    },

    {
        'table_name': 'DERI_INDUSTRY_RISE_RATIO',
        'fields': '*',
        'merge_fields': ['date', 'industry'],
        'drop_fields': ['time_stamp'],
        'prefix': 'INDUSTRY',
        'condition': ""
    },

    {
        'table_name': 'DERI_MARKET_RISE_RATIO',
        'fields': '*',
        'merge_fields': ['date', 'market'],
        'drop_fields': ['time_stamp'],
        'prefix': 'MARKET',
        'condition': ""
    },

    {
        'table_name': 'AREA_INDEX_FORWARD_ADJ_QUOTE',
        'fields': ['date', 'area', 'amount', 'turnover'],
        'merge_fields': ['date', 'area'],
        'drop_fields': [],
        'prefix': 'AREA',
        'condition': ""
    },

    {
        'table_name': 'INDUSTRY_INDEX_FORWARD_ADJ_QUOTE',
        'fields': ['date', 'industry', 'amount', 'turnover'],
        'merge_fields': ['date', 'industry'],
        'drop_fields': [],
        'prefix': 'INDUSTRY',
        'condition': ""
    },

    {
        'table_name': 'STOCK_MARKET_INDEX_QUOTE',
        'fields': ['date', 'market', 'amount'],
        'merge_fields': ['date', 'market'],
        'drop_fields': [],
        'prefix': 'MARKET',
        'condition': ""
    },

    {
        'table_name': 'HS300_QUOTE',
        'fields': ['date', 'amount'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'HS300',
        'condition': ""
    },

    {
        'table_name': 'DERI_AREA_INDEX_FOR_ADJ',
        'fields': ['date', 'area', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D',
                   'AD_DIFF_7D', 'AD_DIFF_14D', 'AD_DIFF_21D', 'AD_DIFF_28D',
                   'ADX_7D', 'ADX_14D', 'ADX_21D', 'ADX_28D',
                   'CCI_7D', 'CCI_14D', 'CCI_21D', 'CCI_28D',
                   'RSI_7D', 'RSI_14D', 'RSI_21D', 'RSI_28D',
                   'STOCH_K_7D', 'STOCH_K_14D', 'STOCH_K_21D', 'STOCH_K_28D',
                   'STOCH_D_7D', 'STOCH_D_14D', 'STOCH_D_21D', 'STOCH_D_28D',
                   'WILLER_7D', 'WILLER_14D', 'WILLER_21D', 'WILLER_28D',
                   'VR_7D', 'VR_14D', 'VR_21D', 'VR_28D',
                   'VOLUME_RATIO', 'TURNOVER_ROLLING_SUM_2D', 'TURNOVER_ROLLING_SUM_5D',
                   'TURNOVER_ROLLING_SUM_10D', 'TURNOVER_ROLLING_SUM_20D', 'TURNOVER_ROLLING_SUM_30D', 'TURNOVER_ROLLING_SUM_60D',
                   'AMPLITUDE_1D', 'AMPLITUDE_2D', 'AMPLITUDE_5D', 'AMPLITUDE_10D', 'AMPLITUDE_20D', 'AMPLITUDE_30D', 'AMPLITUDE_60D'
                   ],
        'merge_fields': ['date', 'area'],
        'drop_fields': [],
        'prefix': 'AREA',
        'condition': ""
    },

{
        'table_name': 'DERI_STAT_AREA_INDEX_FOR_ADJ',
        'fields': '*',
        'merge_fields': ['date', 'area'],
        'drop_fields': ['AMTEMA_2D', 'AMTEMA_5D', 'AMTEMA_10D', 'AMTEMA_20D', 'AMTEMA_30D', 'AMTEMA_60D', 'AMTEMA_120D', 'AMTEMA_250D',
                        'AMTEMA_DIFF_2D', 'AMTEMA_DIFF_SIGN_2D', 'AMTEMA_DIFF_PLUS_COUNT_2D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_2D', 'AMTEMA_DIFF_CON_PLUS_COUNT_2D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTEMA_DIFF_5D', 'AMTEMA_DIFF_SIGN_5D', 'AMTEMA_DIFF_PLUS_COUNT_5D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_5D', 'AMTEMA_DIFF_CON_PLUS_COUNT_5D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTEMA_DIFF_10D', 'AMTEMA_DIFF_SIGN_10D', 'AMTEMA_DIFF_PLUS_COUNT_10D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_10D', 'AMTEMA_DIFF_CON_PLUS_COUNT_10D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTEMA_DIFF_20D', 'AMTEMA_DIFF_SIGN_20D', 'AMTEMA_DIFF_PLUS_COUNT_20D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_20D', 'AMTEMA_DIFF_CON_PLUS_COUNT_20D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTEMA_DIFF_30D', 'AMTEMA_DIFF_SIGN_30D', 'AMTEMA_DIFF_PLUS_COUNT_30D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_30D', 'AMTEMA_DIFF_CON_PLUS_COUNT_30D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTEMA_DIFF_60D', 'AMTEMA_DIFF_SIGN_60D', 'AMTEMA_DIFF_PLUS_COUNT_60D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_60D', 'AMTEMA_DIFF_CON_PLUS_COUNT_60D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTEMA_DIFF_120D', 'AMTEMA_DIFF_SIGN_120D', 'AMTEMA_DIFF_PLUS_COUNT_120D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_120D', 'AMTEMA_DIFF_CON_PLUS_COUNT_120D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTEMA_DIFF_250D', 'AMTEMA_DIFF_SIGN_250D', 'AMTEMA_DIFF_PLUS_COUNT_250D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_250D', 'AMTEMA_DIFF_CON_PLUS_COUNT_250D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'AMTWMA_2D', 'AMTWMA_5D', 'AMTWMA_10D', 'AMTWMA_20D', 'AMTWMA_30D', 'AMTWMA_60D', 'AMTWMA_120D', 'AMTWMA_250D',
                        'AMTWMA_DIFF_2D', 'AMTWMA_DIFF_SIGN_2D', 'AMTWMA_DIFF_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_2D', 'AMTWMA_DIFF_CON_PLUS_COUNT_2D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTWMA_DIFF_5D', 'AMTWMA_DIFF_SIGN_5D', 'AMTWMA_DIFF_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_5D', 'AMTWMA_DIFF_CON_PLUS_COUNT_5D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTWMA_DIFF_10D', 'AMTWMA_DIFF_SIGN_10D', 'AMTWMA_DIFF_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_10D', 'AMTWMA_DIFF_CON_PLUS_COUNT_10D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTWMA_DIFF_20D', 'AMTWMA_DIFF_SIGN_20D', 'AMTWMA_DIFF_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_20D', 'AMTWMA_DIFF_CON_PLUS_COUNT_20D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTWMA_DIFF_30D', 'AMTWMA_DIFF_SIGN_30D', 'AMTWMA_DIFF_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_30D', 'AMTWMA_DIFF_CON_PLUS_COUNT_30D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTWMA_DIFF_60D', 'AMTWMA_DIFF_SIGN_60D', 'AMTWMA_DIFF_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_60D', 'AMTWMA_DIFF_CON_PLUS_COUNT_60D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTWMA_DIFF_120D', 'AMTWMA_DIFF_SIGN_120D', 'AMTWMA_DIFF_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_120D', 'AMTWMA_DIFF_CON_PLUS_COUNT_120D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTWMA_DIFF_250D', 'AMTWMA_DIFF_SIGN_250D', 'AMTWMA_DIFF_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_250D', 'AMTWMA_DIFF_CON_PLUS_COUNT_250D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'time_stamp'],
        'prefix': 'AREA',
        'condition': ""
    },

    {
        'table_name': 'DERI_INDUSTRY_INDEX_FOR_ADJ',
        'fields': ['date', 'industry', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D',
                   'AD_DIFF_7D', 'AD_DIFF_14D', 'AD_DIFF_21D', 'AD_DIFF_28D',
                   'ADX_7D', 'ADX_14D', 'ADX_21D', 'ADX_28D',
                   'CCI_7D', 'CCI_14D', 'CCI_21D', 'CCI_28D',
                   'RSI_7D', 'RSI_14D', 'RSI_21D', 'RSI_28D',
                   'STOCH_K_7D', 'STOCH_K_14D', 'STOCH_K_21D', 'STOCH_K_28D',
                   'STOCH_D_7D', 'STOCH_D_14D', 'STOCH_D_21D', 'STOCH_D_28D',
                   'WILLER_7D', 'WILLER_14D', 'WILLER_21D', 'WILLER_28D',
                   'VR_7D', 'VR_14D', 'VR_21D', 'VR_28D',
                   'VOLUME_RATIO', 'TURNOVER_ROLLING_SUM_2D', 'TURNOVER_ROLLING_SUM_5D',
                   'TURNOVER_ROLLING_SUM_10D', 'TURNOVER_ROLLING_SUM_20D', 'TURNOVER_ROLLING_SUM_30D', 'TURNOVER_ROLLING_SUM_60D',
                   'AMPLITUDE_1D', 'AMPLITUDE_2D', 'AMPLITUDE_5D', 'AMPLITUDE_10D', 'AMPLITUDE_20D', 'AMPLITUDE_30D', 'AMPLITUDE_60D'
                   ],
        'merge_fields': ['date', 'industry'],
        'drop_fields': [],
        'prefix': 'INDUSTRY',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_INDUSTRY_INDEX_FOR_ADJ',
        'fields': '*',
        'merge_fields': ['date', 'industry'],
        'drop_fields': ['AMTEMA_2D', 'AMTEMA_5D', 'AMTEMA_10D', 'AMTEMA_20D', 'AMTEMA_30D', 'AMTEMA_60D', 'AMTEMA_120D', 'AMTEMA_250D',
                        'AMTEMA_DIFF_2D', 'AMTEMA_DIFF_SIGN_2D', 'AMTEMA_DIFF_PLUS_COUNT_2D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_2D', 'AMTEMA_DIFF_CON_PLUS_COUNT_2D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTEMA_DIFF_5D', 'AMTEMA_DIFF_SIGN_5D', 'AMTEMA_DIFF_PLUS_COUNT_5D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_5D', 'AMTEMA_DIFF_CON_PLUS_COUNT_5D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTEMA_DIFF_10D', 'AMTEMA_DIFF_SIGN_10D', 'AMTEMA_DIFF_PLUS_COUNT_10D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_10D', 'AMTEMA_DIFF_CON_PLUS_COUNT_10D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTEMA_DIFF_20D', 'AMTEMA_DIFF_SIGN_20D', 'AMTEMA_DIFF_PLUS_COUNT_20D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_20D', 'AMTEMA_DIFF_CON_PLUS_COUNT_20D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTEMA_DIFF_30D', 'AMTEMA_DIFF_SIGN_30D', 'AMTEMA_DIFF_PLUS_COUNT_30D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_30D', 'AMTEMA_DIFF_CON_PLUS_COUNT_30D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTEMA_DIFF_60D', 'AMTEMA_DIFF_SIGN_60D', 'AMTEMA_DIFF_PLUS_COUNT_60D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_60D', 'AMTEMA_DIFF_CON_PLUS_COUNT_60D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTEMA_DIFF_120D', 'AMTEMA_DIFF_SIGN_120D', 'AMTEMA_DIFF_PLUS_COUNT_120D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_120D', 'AMTEMA_DIFF_CON_PLUS_COUNT_120D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTEMA_DIFF_250D', 'AMTEMA_DIFF_SIGN_250D', 'AMTEMA_DIFF_PLUS_COUNT_250D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_250D', 'AMTEMA_DIFF_CON_PLUS_COUNT_250D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'AMTWMA_2D', 'AMTWMA_5D', 'AMTWMA_10D', 'AMTWMA_20D', 'AMTWMA_30D', 'AMTWMA_60D', 'AMTWMA_120D', 'AMTWMA_250D',
                        'AMTWMA_DIFF_2D', 'AMTWMA_DIFF_SIGN_2D', 'AMTWMA_DIFF_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_2D', 'AMTWMA_DIFF_CON_PLUS_COUNT_2D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTWMA_DIFF_5D', 'AMTWMA_DIFF_SIGN_5D', 'AMTWMA_DIFF_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_5D', 'AMTWMA_DIFF_CON_PLUS_COUNT_5D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTWMA_DIFF_10D', 'AMTWMA_DIFF_SIGN_10D', 'AMTWMA_DIFF_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_10D', 'AMTWMA_DIFF_CON_PLUS_COUNT_10D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTWMA_DIFF_20D', 'AMTWMA_DIFF_SIGN_20D', 'AMTWMA_DIFF_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_20D', 'AMTWMA_DIFF_CON_PLUS_COUNT_20D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTWMA_DIFF_30D', 'AMTWMA_DIFF_SIGN_30D', 'AMTWMA_DIFF_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_30D', 'AMTWMA_DIFF_CON_PLUS_COUNT_30D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTWMA_DIFF_60D', 'AMTWMA_DIFF_SIGN_60D', 'AMTWMA_DIFF_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_60D', 'AMTWMA_DIFF_CON_PLUS_COUNT_60D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTWMA_DIFF_120D', 'AMTWMA_DIFF_SIGN_120D', 'AMTWMA_DIFF_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_120D', 'AMTWMA_DIFF_CON_PLUS_COUNT_120D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTWMA_DIFF_250D', 'AMTWMA_DIFF_SIGN_250D', 'AMTWMA_DIFF_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_250D', 'AMTWMA_DIFF_CON_PLUS_COUNT_250D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'time_stamp'],
        'prefix': 'INDUSTRY',
        'condition': ""
    },

    {
        'table_name': 'DERI_MARKET_INDEX',
        'fields': ['date', 'market', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D',
                   'AD_DIFF_7D', 'AD_DIFF_14D', 'AD_DIFF_21D', 'AD_DIFF_28D',
                   'ADX_7D', 'ADX_14D', 'ADX_21D', 'ADX_28D',
                   'CCI_7D', 'CCI_14D', 'CCI_21D', 'CCI_28D',
                   'RSI_7D', 'RSI_14D', 'RSI_21D', 'RSI_28D',
                   'STOCH_K_7D', 'STOCH_K_14D', 'STOCH_K_21D', 'STOCH_K_28D',
                   'STOCH_D_7D', 'STOCH_D_14D', 'STOCH_D_21D', 'STOCH_D_28D',
                   'WILLER_7D', 'WILLER_14D', 'WILLER_21D', 'WILLER_28D',
                   'VR_7D', 'VR_14D', 'VR_21D', 'VR_28D',
                   'VOLUME_RATIO', 'AMPLITUDE_1D', 'AMPLITUDE_2D', 'AMPLITUDE_5D', 'AMPLITUDE_10D',
                   'AMPLITUDE_20D', 'AMPLITUDE_30D', 'AMPLITUDE_60D'
                   ],
        'merge_fields': ['date', 'market'],
        'drop_fields': [],
        'prefix': 'MARKET',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_MARKET_INDEX',
        'fields': '*',
        'merge_fields': ['date', 'market'],
        'drop_fields': ['AMTEMA_2D', 'AMTEMA_5D', 'AMTEMA_10D', 'AMTEMA_20D', 'AMTEMA_30D', 'AMTEMA_60D', 'AMTEMA_120D', 'AMTEMA_250D',
                        'AMTEMA_DIFF_2D', 'AMTEMA_DIFF_SIGN_2D', 'AMTEMA_DIFF_PLUS_COUNT_2D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_2D', 'AMTEMA_DIFF_CON_PLUS_COUNT_2D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTEMA_DIFF_5D', 'AMTEMA_DIFF_SIGN_5D', 'AMTEMA_DIFF_PLUS_COUNT_5D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_5D', 'AMTEMA_DIFF_CON_PLUS_COUNT_5D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTEMA_DIFF_10D', 'AMTEMA_DIFF_SIGN_10D', 'AMTEMA_DIFF_PLUS_COUNT_10D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_10D', 'AMTEMA_DIFF_CON_PLUS_COUNT_10D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTEMA_DIFF_20D', 'AMTEMA_DIFF_SIGN_20D', 'AMTEMA_DIFF_PLUS_COUNT_20D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_20D', 'AMTEMA_DIFF_CON_PLUS_COUNT_20D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTEMA_DIFF_30D', 'AMTEMA_DIFF_SIGN_30D', 'AMTEMA_DIFF_PLUS_COUNT_30D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_30D', 'AMTEMA_DIFF_CON_PLUS_COUNT_30D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTEMA_DIFF_60D', 'AMTEMA_DIFF_SIGN_60D', 'AMTEMA_DIFF_PLUS_COUNT_60D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_60D', 'AMTEMA_DIFF_CON_PLUS_COUNT_60D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTEMA_DIFF_120D', 'AMTEMA_DIFF_SIGN_120D', 'AMTEMA_DIFF_PLUS_COUNT_120D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_120D', 'AMTEMA_DIFF_CON_PLUS_COUNT_120D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTEMA_DIFF_250D', 'AMTEMA_DIFF_SIGN_250D', 'AMTEMA_DIFF_PLUS_COUNT_250D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_250D', 'AMTEMA_DIFF_CON_PLUS_COUNT_250D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'AMTWMA_2D', 'AMTWMA_5D', 'AMTWMA_10D', 'AMTWMA_20D', 'AMTWMA_30D', 'AMTWMA_60D', 'AMTWMA_120D', 'AMTWMA_250D',
                        'AMTWMA_DIFF_2D', 'AMTWMA_DIFF_SIGN_2D', 'AMTWMA_DIFF_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_2D', 'AMTWMA_DIFF_CON_PLUS_COUNT_2D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTWMA_DIFF_5D', 'AMTWMA_DIFF_SIGN_5D', 'AMTWMA_DIFF_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_5D', 'AMTWMA_DIFF_CON_PLUS_COUNT_5D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTWMA_DIFF_10D', 'AMTWMA_DIFF_SIGN_10D', 'AMTWMA_DIFF_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_10D', 'AMTWMA_DIFF_CON_PLUS_COUNT_10D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTWMA_DIFF_20D', 'AMTWMA_DIFF_SIGN_20D', 'AMTWMA_DIFF_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_20D', 'AMTWMA_DIFF_CON_PLUS_COUNT_20D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTWMA_DIFF_30D', 'AMTWMA_DIFF_SIGN_30D', 'AMTWMA_DIFF_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_30D', 'AMTWMA_DIFF_CON_PLUS_COUNT_30D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTWMA_DIFF_60D', 'AMTWMA_DIFF_SIGN_60D', 'AMTWMA_DIFF_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_60D', 'AMTWMA_DIFF_CON_PLUS_COUNT_60D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTWMA_DIFF_120D', 'AMTWMA_DIFF_SIGN_120D', 'AMTWMA_DIFF_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_120D', 'AMTWMA_DIFF_CON_PLUS_COUNT_120D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTWMA_DIFF_250D', 'AMTWMA_DIFF_SIGN_250D', 'AMTWMA_DIFF_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_250D', 'AMTWMA_DIFF_CON_PLUS_COUNT_250D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'time_stamp'],
        'prefix': 'MARKET',
        'condition': ""
    },

    {
        'table_name': 'DERI_HS300',
        'fields': ['date', 'MA_DIFF_SIGN_2D', 'MA_DIFF_PLUS_COUNT_2D',
                    'MA_DIFF_NEGATIVE_COUNT_2D', 'MA_DIFF_CON_PLUS_COUNT_2D', 'MA_DIFF_CON_NEGATIVE_COUNT_2D',
                    'MA_DIFF_SIGN_5D', 'MA_DIFF_PLUS_COUNT_5D',
                    'MA_DIFF_NEGATIVE_COUNT_5D', 'MA_DIFF_CON_PLUS_COUNT_5D', 'MA_DIFF_CON_NEGATIVE_COUNT_5D',
                    'MA_DIFF_SIGN_10D', 'MA_DIFF_PLUS_COUNT_10D',
                    'MA_DIFF_NEGATIVE_COUNT_10D', 'MA_DIFF_CON_PLUS_COUNT_10D', 'MA_DIFF_CON_NEGATIVE_COUNT_10D',
                    'MA_DIFF_SIGN_20D', 'MA_DIFF_PLUS_COUNT_20D',
                    'MA_DIFF_NEGATIVE_COUNT_20D', 'MA_DIFF_CON_PLUS_COUNT_20D', 'MA_DIFF_CON_NEGATIVE_COUNT_20D',
                    'MA_DIFF_SIGN_30D', 'MA_DIFF_PLUS_COUNT_30D',
                    'MA_DIFF_NEGATIVE_COUNT_30D', 'MA_DIFF_CON_PLUS_COUNT_30D', 'MA_DIFF_CON_NEGATIVE_COUNT_30D',
                    'MA_DIFF_SIGN_60D', 'MA_DIFF_PLUS_COUNT_60D',
                    'MA_DIFF_NEGATIVE_COUNT_60D', 'MA_DIFF_CON_PLUS_COUNT_60D', 'MA_DIFF_CON_NEGATIVE_COUNT_60D',
                    'RET_1D', 'RET_2D', 'RET_5D', 'RET_10D', 'RET_20D', 'RET_30D', 'RET_60D',
                   'STD_5D', 'STD_10D', 'STD_20D', 'STD_30D', 'STD_60D',
                   'MACD_DIF_12_26D', 'MACD_DEA_12_26_7D', 'MACD_DEA_12_26_14D', 'MACD_DEA_12_26_21D', 'MACD_DEA_12_26_28D',
                   'MACD_12_26_7D', 'MACD_12_26_14D', 'MACD_12_26_21D', 'MACD_12_26_28D',
                   'AD_DIFF_7D', 'AD_DIFF_14D', 'AD_DIFF_21D', 'AD_DIFF_28D',
                   'ADX_7D', 'ADX_14D', 'ADX_21D', 'ADX_28D',
                   'CCI_7D', 'CCI_14D', 'CCI_21D', 'CCI_28D',
                   'RSI_7D', 'RSI_14D', 'RSI_21D', 'RSI_28D',
                   'STOCH_K_7D', 'STOCH_K_14D', 'STOCH_K_21D', 'STOCH_K_28D',
                   'STOCH_D_7D', 'STOCH_D_14D', 'STOCH_D_21D', 'STOCH_D_28D',
                   'WILLER_7D', 'WILLER_14D', 'WILLER_21D', 'WILLER_28D',
                   'VR_7D', 'VR_14D', 'VR_21D', 'VR_28D',
                   'VOLUME_RATIO'],
        'merge_fields': ['date'],
        'drop_fields': [],
        'prefix': 'HS300',
        'condition': ""
    },

    {
        'table_name': 'DERI_STAT_HS300',
        'fields': '*',
        'merge_fields': ['date'],
        'drop_fields': ['AMTEMA_2D', 'AMTEMA_5D', 'AMTEMA_10D', 'AMTEMA_20D', 'AMTEMA_30D', 'AMTEMA_60D', 'AMTEMA_120D', 'AMTEMA_250D',
                        'AMTEMA_DIFF_2D', 'AMTEMA_DIFF_SIGN_2D', 'AMTEMA_DIFF_PLUS_COUNT_2D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_2D', 'AMTEMA_DIFF_CON_PLUS_COUNT_2D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTEMA_DIFF_5D', 'AMTEMA_DIFF_SIGN_5D', 'AMTEMA_DIFF_PLUS_COUNT_5D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_5D', 'AMTEMA_DIFF_CON_PLUS_COUNT_5D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTEMA_DIFF_10D', 'AMTEMA_DIFF_SIGN_10D', 'AMTEMA_DIFF_PLUS_COUNT_10D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_10D', 'AMTEMA_DIFF_CON_PLUS_COUNT_10D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTEMA_DIFF_20D', 'AMTEMA_DIFF_SIGN_20D', 'AMTEMA_DIFF_PLUS_COUNT_20D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_20D', 'AMTEMA_DIFF_CON_PLUS_COUNT_20D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTEMA_DIFF_30D', 'AMTEMA_DIFF_SIGN_30D', 'AMTEMA_DIFF_PLUS_COUNT_30D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_30D', 'AMTEMA_DIFF_CON_PLUS_COUNT_30D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTEMA_DIFF_60D', 'AMTEMA_DIFF_SIGN_60D', 'AMTEMA_DIFF_PLUS_COUNT_60D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_60D', 'AMTEMA_DIFF_CON_PLUS_COUNT_60D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTEMA_DIFF_120D', 'AMTEMA_DIFF_SIGN_120D', 'AMTEMA_DIFF_PLUS_COUNT_120D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_120D', 'AMTEMA_DIFF_CON_PLUS_COUNT_120D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTEMA_DIFF_250D', 'AMTEMA_DIFF_SIGN_250D', 'AMTEMA_DIFF_PLUS_COUNT_250D',
                        'AMTEMA_DIFF_NEGATIVE_COUNT_250D', 'AMTEMA_DIFF_CON_PLUS_COUNT_250D', 'AMTEMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'AMTWMA_2D', 'AMTWMA_5D', 'AMTWMA_10D', 'AMTWMA_20D', 'AMTWMA_30D', 'AMTWMA_60D', 'AMTWMA_120D', 'AMTWMA_250D',
                        'AMTWMA_DIFF_2D', 'AMTWMA_DIFF_SIGN_2D', 'AMTWMA_DIFF_PLUS_COUNT_2D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_2D', 'AMTWMA_DIFF_CON_PLUS_COUNT_2D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_2D',
                        'AMTWMA_DIFF_5D', 'AMTWMA_DIFF_SIGN_5D', 'AMTWMA_DIFF_PLUS_COUNT_5D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_5D', 'AMTWMA_DIFF_CON_PLUS_COUNT_5D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_5D',
                        'AMTWMA_DIFF_10D', 'AMTWMA_DIFF_SIGN_10D', 'AMTWMA_DIFF_PLUS_COUNT_10D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_10D', 'AMTWMA_DIFF_CON_PLUS_COUNT_10D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_10D',
                        'AMTWMA_DIFF_20D', 'AMTWMA_DIFF_SIGN_20D', 'AMTWMA_DIFF_PLUS_COUNT_20D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_20D', 'AMTWMA_DIFF_CON_PLUS_COUNT_20D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_20D',
                        'AMTWMA_DIFF_30D', 'AMTWMA_DIFF_SIGN_30D', 'AMTWMA_DIFF_PLUS_COUNT_30D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_30D', 'AMTWMA_DIFF_CON_PLUS_COUNT_30D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_30D',
                        'AMTWMA_DIFF_60D', 'AMTWMA_DIFF_SIGN_60D', 'AMTWMA_DIFF_PLUS_COUNT_60D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_60D', 'AMTWMA_DIFF_CON_PLUS_COUNT_60D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_60D',
                        'AMTWMA_DIFF_120D', 'AMTWMA_DIFF_SIGN_120D', 'AMTWMA_DIFF_PLUS_COUNT_120D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_120D', 'AMTWMA_DIFF_CON_PLUS_COUNT_120D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_120D',
                        'AMTWMA_DIFF_250D', 'AMTWMA_DIFF_SIGN_250D', 'AMTWMA_DIFF_PLUS_COUNT_250D',
                        'AMTWMA_DIFF_NEGATIVE_COUNT_250D', 'AMTWMA_DIFF_CON_PLUS_COUNT_250D', 'AMTWMA_DIFF_CON_NEGATIVE_COUNT_250D',
                        'time_stamp'],
        'prefix': 'HS300',
        'condition': ""
    },
]

areaConf = {
    'table_name': 'STOCK_DESCRIPTION',
    'fields': ['code', 'area'],
    'merge_fields': ['code'],
}